import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import Header from "../app/components/Header/Header";
import Footer from "./components/Footer/Footer";

const recoleta = localFont({
  src: [
  {
  path: "../../public/fonts/Recoleta-Black.ttf",
  weight: "400",
  },
  {
  path: "../../public/fonts/Recoleta-Medium.ttf",
  weight: "300",
  },
  {
  path: "../../public/fonts/Recoleta-Light.ttf",
  weight: "200",
  },
  ],
  variable: "--font-recoleta",
  display: "swap",
  });

export const metadata: Metadata = {
  title: "Nibir's Portfolio Website",
  description: "Generated by Md. Moinul Hossain Nibir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="{recoleta.variable}">
      <body suppressHydrationWarning={true} className={recoleta.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
